- name: Deploy application
  hosts: webservers
  remote_user: git
  become: yes
  roles:
    - deploy-application

- name: Save application location
  hosts: databases
  remote_user: john
  become: yes
  with_dict: "{{ (groups['webservers'] | map('extract', hostvars, 'port_map') | list | first) }}"
  roles:
    name: save-application-location
  vars:
    application_name: "{{ item.key }}"
    application_port: "{{ item.value }}"
