
- name: Create repository
  command: git init --bare "{{ servers_path }}/{{ application_name }}.git"
  args:
    creates: "{{ servers_path }}/{{ application_name }}.git/HEAD"

- name: Set permissions
    file:
      path: "{{ servers_path }}/{{ application_name }}.git"
      state: directory
      mode: 0755
      owner: git
      group: git
      recurse: True
