- name: Retrieve tag
  community.mongodb.mongodb_shell:
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    login_database: "{{ db_name }}"
    db: "{{ db_name }}"
    eval: "db.deployments.find({ 'application.name': { $eq: '{{ application_name }}' } }).limit(1).sort({$natural:-1})"
    debug: yes
  register: res

- name: Save deployment
  set_fact:
    deployment_tag: "{{ res.out | regex_search('\"tag\" ?: ?\"([a-zA-Z0-9-]+)\"', '\\1') | first }}"
