- name: Check if repository exists.
  stat:
    path: "{{ repositories_path }}/{{ application_name }}"
  register: repository

- name: Remove repository directory
  shell: rm -rf "{{ repositories_path }}/{{ application_name }}"
  when: repository.stat.exists

- name: Clone repository
  shell: git clone "{{ servers_path }}/{{ application_name }}.git" "{{ repositories_path }}/{{ application_name }}"
