- name: Check if repository exists.
  stat:
    path: "{{ servers_path }}/{{ application_name }}.git"
  register: repository

- name: Create repository directory
  shell: rm -rf "{{ servers_path }}/{{ application_name }}.git"
  when: repository.stat.exists == false

- name: Clone repository
  shell: git clone "{{ servers_path }}/{{ application_name }}.git" "{{ repositories_path }}/{{ application_name }}"
