
- name: Clone repository
  import_tasks: clone-repository.yml

- name: Clean container
  import_tasks: clean-container.yml

- name: Install dependencies
  import_tasks: install-dependencies.yml

- name: Connect to database
  import_tasks: connect-db.yml

- name: Save location
  import_tasks: retrieve-tag.yml

- name: Run container
  import_tasks: run-container.yml
