- name: Find available port
  shell: |
    PORT=5000
    while true; do
      ss -tulpen | grep ":${PORT}" &> /dev/null
      if [[ "$?" == "1" ]]; then
        echo "${PORT}"
        exit
      fi
      ((PORT++))
    done
  args:
    executable: /bin/bash
  register: port

- name: Check if Dockerfile exists
  stat:
    path: "{{ repositories_path }}/{{ application_name }}/Dockerfile"
  register: stat_result

- name: Build image
  shell: docker build -t "{{ application_name }}:latest" {{ repositories_path }}/{{ application_name }}
  when: stat_result.stat.exists

- name: Run container
  shell: docker run -d -p "{{ port.stdout }}:80" --name "{{ application_name }}" "{{ application_name }}:latest"
  when: stat_result.stat.exists

- name: Save port
  set_fact:
    port_map: "{{ port_map | default({}) | combine ({ application_name : port.stdout }) }}"
  when: stat_result.stat.exists
