- name: Find available port
  shell: |
    PORT=5000
    while true; do
      ss -tulpen | grep ":${PORT}" &> /dev/null
      if [[ "$?" == "1" ]]; then
        echo "${PORT}"
        exit
      fi
      ((PORT++))
    done
  args:
    executable: /bin/bash
  register: port

- name: Build image
  shell: sudo docker build -t "{{ application_name }}:latest" "{{ repositories_path }}/{{ application_name }}"

- name: Run container
  shell: sudo docker run -d -p "{{ port.stdout }}:80" --name "{{ application_name }}" "{{ application_name }}:latest"

- name: Save port
  community.mongodb.mongodb_shell:
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    login_database: "{{ db_name }}"
    db: "{{ db_name }}"
    eval: "db.ports.replaceOne({ name: { $eq: '{{ application_name }}' } }, { name: '{{ application_name }}', port: '{{ port.stdout }}' }, {upsert: true})"
